"""add_network_constraints

Revision ID: 0f48779f3aaa
Revises: 23058907d24b
Create Date: 2026-08-09 14:30:26.085768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f48779f3aaa'
down_revision: Union[str, Sequence[str], None] = '23058907d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_patient_caretaker_network', 'patient_caretaker_networks', ['patient_id', 'caretaker_id'])
    op.create_unique_constraint('uix_patient_doctor_network', 'patient_doctor_networks', ['patient_id', 'doctor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_predictions_user_completed'), 'predictions', ['user_id', sa.literal_column('completed_at DESC')], unique=False)
    op.drop_constraint('uix_patient_doctor_network', 'patient_doctor_networks', type_='unique')
    op.drop_constraint('uix_patient_caretaker_network', 'patient_caretaker_networks', type_='unique')
    op.create_index(op.f('ix_medication_logs_user_taken'), 'medication_logs', ['user_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_eeg_sessions_user_created'), 'eeg_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_rag_chunks_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    # ### end Alembic commands ###
