"""Add RBAC roles profiles and networks

Revision ID: 23058907d24b
Revises: f42c7d723bd0
Create Date: 2026-08-09 13:59:45.608830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23058907d24b'
down_revision: Union[str, Sequence[str], None] = 'f42c7d723bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretaker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_to_patient', sa.String(length=100), nullable=True),
    sa.Column('crisis_phone_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caretaker_profiles_id'), 'caretaker_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_caretaker_profiles_user_id'), 'caretaker_profiles', ['user_id'], unique=True)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pmdc_number', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('hospital_affiliation', sa.String(length=200), nullable=True),
    sa.Column('license_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_pmdc_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_pmdc_number'), 'doctor_profiles', ['pmdc_number'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    
    connection_status_enum_create = postgresql.ENUM('PENDING', 'ACTIVE', 'REVOKED', name='connection_status_enum', create_type=True)
    connection_status_enum_no_create = postgresql.ENUM('PENDING', 'ACTIVE', 'REVOKED', name='connection_status_enum', create_type=False)

    op.create_table('patient_caretaker_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.Column('relationship_status', connection_status_enum_create, nullable=False),
    sa.Column('date_linked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['caretaker_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_caretaker_networks_caretaker_id'), 'patient_caretaker_networks', ['caretaker_id'], unique=False)
    op.create_index(op.f('ix_patient_caretaker_networks_id'), 'patient_caretaker_networks', ['id'], unique=False)
    op.create_index(op.f('ix_patient_caretaker_networks_patient_id'), 'patient_caretaker_networks', ['patient_id'], unique=False)
    op.create_table('patient_doctor_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('relationship_status', connection_status_enum_no_create, nullable=False),
    sa.Column('date_linked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_doctor_networks_doctor_id'), 'patient_doctor_networks', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_doctor_networks_id'), 'patient_doctor_networks', ['id'], unique=False)
    op.create_index(op.f('ix_patient_doctor_networks_patient_id'), 'patient_doctor_networks', ['patient_id'], unique=False)
    op.add_column('patient_profiles', sa.Column('blood_type', sa.String(length=10), nullable=True))
    op.add_column('patient_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('primary_diagnosis', sa.String(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_contact_relation', sa.String(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))
    op.alter_column('patient_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('patient_profiles', 'height_cm')
    op.drop_column('patient_profiles', 'full_name')
    op.drop_column('patient_profiles', 'weight_kg')
    user_role_enum = postgresql.ENUM('PATIENT', 'DOCTOR', 'CARETAKER', 'ADMIN', name='user_role_enum')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('role', user_role_enum, server_default='PATIENT', nullable=False))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    op.create_index(op.f('ix_predictions_user_completed'), 'predictions', ['user_id', sa.literal_column('completed_at DESC')], unique=False)
    op.add_column('patient_profiles', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patient_profiles', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('patient_profiles', sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('patient_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('patient_profiles', 'emergency_contact_phone')
    op.drop_column('patient_profiles', 'emergency_contact_relation')
    op.drop_column('patient_profiles', 'emergency_contact_name')
    op.drop_column('patient_profiles', 'primary_diagnosis')
    op.drop_column('patient_profiles', 'city')
    op.drop_column('patient_profiles', 'blood_type')
    op.create_index(op.f('ix_medication_logs_user_taken'), 'medication_logs', ['user_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_eeg_sessions_user_created'), 'eeg_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_patient_doctor_networks_patient_id'), table_name='patient_doctor_networks')
    op.drop_index(op.f('ix_patient_doctor_networks_id'), table_name='patient_doctor_networks')
    op.drop_index(op.f('ix_patient_doctor_networks_doctor_id'), table_name='patient_doctor_networks')
    op.drop_table('patient_doctor_networks')
    op.drop_index(op.f('ix_patient_caretaker_networks_patient_id'), table_name='patient_caretaker_networks')
    op.drop_index(op.f('ix_patient_caretaker_networks_id'), table_name='patient_caretaker_networks')
    op.drop_index(op.f('ix_patient_caretaker_networks_caretaker_id'), table_name='patient_caretaker_networks')
    op.drop_table('patient_caretaker_networks')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_pmdc_number'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_caretaker_profiles_user_id'), table_name='caretaker_profiles')
    op.drop_index(op.f('ix_caretaker_profiles_id'), table_name='caretaker_profiles')
    op.drop_table('caretaker_profiles')
    # ### end Alembic commands ###
