"""Add fcm_token

Revision ID: 6c8f25f56b3e
Revises: 0f48779f3aaa
Create Date: 2026-08-09 20:35:12.789077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8f25f56b3e'
down_revision: Union[str, Sequence[str], None] = '0f48779f3aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Safe index drop via raw SQL string execution
    op.execute("DROP INDEX IF EXISTS ix_apscheduler_jobs_next_run_time;")
    
    # Safe table drop via raw SQL string execution
    op.execute("DROP TABLE IF EXISTS apscheduler_jobs;")
    
    op.drop_index(op.f('ix_chat_messages_session_created'), table_name='chat_messages')
    op.drop_index(op.f('ix_eeg_sessions_user_created'), table_name='eeg_sessions')
    op.drop_index(op.f('ix_medication_logs_user_taken'), table_name='medication_logs')
    op.drop_index(op.f('ix_predictions_user_completed'), table_name='predictions')
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.create_index(op.f('ix_predictions_user_completed'), 'predictions', ['user_id', sa.literal_column('completed_at DESC')], unique=False)
    op.create_index(op.f('ix_medication_logs_user_taken'), 'medication_logs', ['user_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_eeg_sessions_user_created'), 'eeg_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
