"""Add PendingRegistration table

Revision ID: 7d5c9aa302cc
Revises: e8b1a2c3d4e5
Create Date: 2026-08-17 20:06:01.490726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7d5c9aa302cc'
down_revision: Union[str, Sequence[str], None] = 'e8b1a2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', postgresql.ENUM('PATIENT', 'DOCTOR', 'CARETAKER', 'ADMIN', name='user_role_enum', create_type=False), nullable=False),
    sa.Column('pmdc_number', sa.String(length=50), nullable=True),
    sa.Column('otp_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=True)
    op.create_index(op.f('ix_pending_registrations_id'), 'pending_registrations', ['id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('ix_chat_messages_user_created'), table_name='chat_messages')
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_user_updated'), table_name='chat_sessions')
    op.create_index('ix_chat_sessions_user_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_sessions_user_updated', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_updated'), 'chat_sessions', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user_created'), 'chat_messages', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_pending_registrations_id'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
