"""Add manual seizures and lifestyle metadata

Revision ID: 928d3b7d19a9
Revises: 6c8f25f56b3e
Create Date: 2026-08-09 20:59:40.767558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '928d3b7d19a9'
down_revision: Union[str, Sequence[str], None] = '6c8f25f56b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_seizure_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('seizure_type', sa.String(length=100), nullable=True),
    sa.Column('auras_felt', sa.Text(), nullable=True),
    sa.Column('post_ictal_symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_seizure_logs_id'), 'manual_seizure_logs', ['id'], unique=False)
    op.create_index(op.f('ix_manual_seizure_logs_occurred_at'), 'manual_seizure_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_manual_seizure_logs_user_id'), 'manual_seizure_logs', ['user_id'], unique=False)
    op.add_column('lifestyle_logs', sa.Column('metadata_dict', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifestyle_logs', 'metadata_dict')

    op.drop_index(op.f('ix_manual_seizure_logs_user_id'), table_name='manual_seizure_logs')
    op.drop_index(op.f('ix_manual_seizure_logs_occurred_at'), table_name='manual_seizure_logs')
    op.drop_index(op.f('ix_manual_seizure_logs_id'), table_name='manual_seizure_logs')
    op.drop_table('manual_seizure_logs')
    # ### end Alembic commands ###
