"""Add email verification fields

Revision ID: f42c7d723bd0
Revises: 202608080001
Create Date: 2026-08-09 12:44:19.168803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f42c7d723bd0'
down_revision: Union[str, Sequence[str], None] = '202608080001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('otp_secret_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_secret_hash')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_rag_chunks_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    # ### end Alembic commands ###
